return {
	mod_title = {
		en = "Custom Flames",
		de = "Benutzerdefinierte Flammen",
		fr = "Flammes personnalisées",
		ru = "Настройка огня",
		["zh-cn"] = "自定义火焰",
	},
	mod_description = {
		en = "Customize your flames with a variety of styles and colors!",
		de = "Passe deine Flammen mit verschiedenen Stilen und Farben an!",
		fr = "Personnalisez vos flammes avec une variété de styles et de couleurs !",
		ru = "Настройте свои огненные стили и цвета!",
		["zh-cn"] = "使用各种风格和颜色自定义您的火焰！",
	},
	feature_toggles = {
		en = "Options",
		de = "Optionen",
		fr = "Options",
		ru = "Опции",
		["zh-cn"] = "选项",
	},
	flamer_burst = {
		en = "Orange Burst Flame Style",
		de = "Oranger Burst-Flammenstil",
		fr = "Style de flamme éclatante orange",
		ru = "Оранжевый взрывной стиль огня",
		["zh-cn"] = "橙色爆裂火焰风格",
	},
	flamer_burst_tooltip = {
		en = "The primary fire for Zealot Orange, which fires a short burst.",
		de = "Der primäre Feuermodus für Zealot Orange, der einen kurzen Burst abfeuert.",
		fr = "Le tir principal pour le flamer orange, qui tire une courte rafale.",
		ru = "Основной огонь для Zealot Orange, стреляющий короткими всплесками.",
		["zh-cn"] = "Zealot橙色的主要火焰，可以发射短暂爆发。",
	},
	flamer_burst1 = {
		en = "Pilot Light",
		de = "Pilotlicht",
		fr = "Lumière pilote",
		ru = "Колышащийся свет",
		["zh-cn"] = "引导光",
	},
	flamer_burst2 = {
		en = "Small Shots",
		de = "Kleine Schüsse",
		fr = "Petits tirs",
		ru = "Маленькие выстрелы",
		["zh-cn"] = "小射击",
	},
	flamer_burst3 = {
		en = "Short Blast",
		de = "Kurzer Blast",
		fr = "Courte explosion",
		ru = "Короткий взрыв",
		["zh-cn"] = "短爆",
	},
	flamer_burstD = {
		en = "Default Burst",
		de = "Standard Burst",
		fr = "Rafale par défaut",
		ru = "Стандартный взрыв",
		["zh-cn"] = "默认爆裂",
	},
	flamer_held = {
		en = "Orange Charged Flame Style",
		de = "Oranger aufgeladener Flammenstil",
		fr = "Style de flamme orange chargé",
		ru = "Заряженный стиль оранжевого пламени",
		["zh-cn"] = "橙色充能火焰样式",
	},
	flamer_held_tooltip = {
		en = "The secondary fire for Zealot Orange, which fires a continuous stream.",
		de = "Der Sekundärschuss für Zealot Orange, der einen kontinuierlichen Strom auslöst.",
		fr = "Le tir secondaire pour Zealot Orange, qui tire un flux continu.",
		ru = "Вторичный огонь для Зелот Оранжевого, стреляющий непрерывным потоком.",
		["zh-cn"] = "Zealot Orange的辅助火焰，发射连续流。",
	},
	flamer_held1 = {
		en = "Clean Stream",
		de = "Sauberer Strom",
		fr = "Flux propre",
		ru = "Чистый поток",
		["zh-cn"] = "清流",
	},
	flamer_held2 = {
		en = "Forceful Blaze",
		de = "Kraftvolle Flamme",
		fr = "Flamme puissante",
		ru = "Мощный огонь",
		["zh-cn"] = "强力火焰",
	},
	flamer_held3 = {
		en = "Rising Flame",
		de = "Aufsteigende Flamme",
		fr = "Flamme montante",
		ru = "Восходящее пламя",
		["zh-cn"] = "上升火焰",
	},
	flamer_heldD = {
		en = "Default Spread",
		de = "Standardverteilung",
		fr = "Étalement par défaut",
		ru = "Стандартное распределение",
		["zh-cn"] = "默认扩散",
	},
	
	flamestaff_burst = {
		en = "Blue Burst Flame Style",
		de = "Blauer aufgebrochener Flammenstil",
		fr = "Style de flamme bleue explosif",
		ru = "Стиль голубого взрыва пламени",
		["zh-cn"] = "蓝色爆炸火焰样式",
	},
	flamestaff_burst_tooltip = {
		en = "The primary fire style for Psyker Blue, which fires a short burst.",
		de = "Der Primärschuss für Psyker Blue, der einen kurzen Ausbruch auslöst.",
		fr = "Le style de tir primaire pour Psyker Blue, qui tire une courte salve.",
		ru = "Первичный стиль стрельбы для Psyker Blue, который выстреливает короткий взрыв.",
		["zh-cn"] = "Psyker Blue的主要火焰样式，发射短暂的爆炸。",
	},
	flamestaff_burst1 = {
		en = "Quick Puff",
		de = "Schneller Stoß",
		fr = "Bouffée rapide",
		ru = "Быстрый пшик",
		["zh-cn"] = "快速喷射",
	},
	flamestaff_burst2 = {
		en = "Rapid Wisps",
		de = "Schnelle Wisper",
		fr = "Sifflements rapides",
		ru = "Быстрые вихри",
		["zh-cn"] = "快速涡流",
	},
	flamestaff_burst3 = {
		en = "Short Blast",
		de = "Kurzer Ausbruch",
		fr = "Courte rafale",
		ru = "Короткий взрыв",
		["zh-cn"] = "短暂冲击",
	},
	flamestaff_burstD = {
		en = "Default Burst",
		de = "Standardstoß",
		fr = "Rafale par défaut",
		ru = "Стандартный взрыв",
		["zh-cn"] = "默认喷射",
	},
	flamestaff_held = {
		en = "Blue Charged Flame Style",
		de = "Blauer aufgeladener Flammenstil",
		fr = "Style de flamme bleue chargée",
		ru = "Заряженный голубой стиль пламени",
		["zh-cn"] = "蓝色充能火焰风格",
	},
	flamestaff_held_tooltip = {
		en = "The secondary fire style for Psyker Blue, which fires a continuous stream.",
		de = "Die Sekundärfeuerart für Psyker Blue, die einen kontinuierlichen Strom feuert.",
		fr = "Le style de tir secondaire pour Psyker Blue, qui tire un flux continu.",
		ru = "Вторичный стиль стрельбы для Psyker Blue, который стреляет непрерывным потоком.",
		["zh-cn"] = "Psyker Blue的次要火力风格，可以持续射击。",
	},
	flamestaff_held1 = {
		en = "Mini Match",
		de = "Minifeuerzeug",
		fr = "Mini-allumette",
		ru = "Мини-спичка",
		["zh-cn"] = "迷你火柴",
	},
	flamestaff_held2 = {
		en = "Octane Flare",
		de = "Octan-Flamme",
		fr = "Flamme d'octane",
		ru = "Октановая вспышка",
		["zh-cn"] = "辛烷闪光",
	},
	flamestaff_held3 = {
		en = "Intermittent Torch",
		de = "Intermittierende Fackel",
		fr = "Torche intermittente",
		ru = "Периодический факел",
		["zh-cn"] = "间歇火炬",
	},
	flamestaff_heldD = {
		en = "Default Spread",
		de = "Standardverbreitung",
		fr = "Diffusion par défaut",
		ru = "Стандартное распространение",
		["zh-cn"] = "默认扩散",
	},

	flamer_color = {
		en = "Flamer Type",
		de = "Flamertyp",
		fr = "Type de lance-flammes",
		ru = "Тип огнемета",
		["zh-cn"] = "喷火枪类型",
	},
	flamer_color_tooltip = {
		en = "The type of flame used by the Zealot Flamer, such as Psyker blue, Cultist green, or Nurgle vomit. Enemy flame types are not customizable.",
		de = "Der Typ der Flamme, die vom Zealot-Flamer verwendet wird, wie zum Beispiel Psyker Blau, Kultistengrün oder Nurgle Erbrochenes. Feindliche Flammentypen sind nicht anpassbar.",
		fr = "Le type de flamme utilisé par le lance-flammes du Zélateur, tel que le bleu Psyker, le vert Cultiste ou le vomi de Nurgle. Les types de flamme ennemis ne sont pas personnalisables.",
		ru = "Тип пламени, используемый Огнеметом ревнителя, такой как псайкер синий, культист зеленый или рвота Нургла. Типы огня врагов не настраиваются.",
		["zh-cn"] = "喷火枪使用的火焰类型，如Psyker蓝色，Cultist绿色或Nurgle呕吐物。敌人的火焰类型不可定制。",
	},
	flamestaff_color = {
		en = "Flamestaff Type",
		de = "Flammenstabtyp",
		fr = "Type de bâton-flamme",
		ru = "Тип огненного посоха",
		["zh-cn"] = "火焰法杖类型",
	},
	flamestaff_color_tooltip = {
		en = "The type of flame used by the Psyker Flamestaff, such as Psyker blue, Cultist green, or Nurgle vomit. Enemy flame types are not customizable.",
		de = "Der Typ der Flamme, die vom Psyker-Flammenstab verwendet wird, wie zum Beispiel Psyker Blau, Kultistengrün oder Nurgle Erbrochenes. Feindliche Flammentypen sind nicht anpassbar.",
		fr = "Le type de flamme utilisé par le bâton-flamme du Psyker, tel que le bleu Psyker, le vert Cultiste ou le vomi de Nurgle. Les types de flamme ennemis ne sont pas personnalisables.",
		ru = "Тип пламени, используемый пламенным посохом Псайкера, такой как псайкер синий, культист зеленый или рвота Нургла. Типы огня врагов не настраиваются.",
		["zh-cn"] = "火焰法杖使用的火焰类型，如Psyker蓝色，Cultist绿色或Nurgle呕吐物。敌人的火焰类型不可定制。",
	},
	flame_color1 = {
		en = "Zealot Orange",
		de = "Zealot-Orange",
		fr = "Orange du Zélote",
		ru = "Огненный гнев заклинателя",
		["zh-cn"] = "狂热者橙色",
	},
	flame_color2 = {
		en = "Psyker Blue",
		de = "Psyker-Blau",
		fr = "Bleu du Psyker",
		ru = "Синий огонь чародея",
		["zh-cn"] = "灵能蓝",
	},
	flame_color3 = {
		en = "Cultist Green",
		de = "Kultistengrün",
		fr = "Vert du Cultiste",
		ru = "Зеленый огонь культиста",
		["zh-cn"] = "异教徒绿色",
	},
	flame_color4 = {
		en = "Scab Orange",
		de = "Krater-Orange",
		fr = "Orange du Scab",
		ru = "Огненный набалдашник",
		["zh-cn"] = "伤痕橙色",
	},
	flame_color5 = {
		en = "Nurgle Vomit",
		de = "Nurgles Erbrochenes",
		fr = "Vomi de Nurgle",
		ru = "Послание Нургла",
		["zh-cn"] = "努格尔呕吐",
	},
}